/* eslint-disable */
/* prettier-ignore */
/* auto-generated by NAPI-RS */

// lib.rs exports
export function getPlatform(): Promise<string>
export function getArch(): Promise<string>
export function readFileText(path: string): Promise<string>
export function writeFileText(path: string, content: string): Promise<boolean>
export function fileExists(path: string): Promise<boolean>
export function isDirectory(path: string): Promise<boolean>
export function getFileSize(path: string): Promise<number>
export function listDirectory(path: string): Promise<string[]>
export function gitStatusFast(repoPath: string): Promise<string>
export function searchFiles(root: string, pattern: string, maxDepth?: number | null): Promise<string[]>
export function pathJoin(a: string, b: string): string
export function pathBasename(path: string): string
export function pathDirname(path: string): string
export function pathExtension(path: string): string
export function getHomeDir(): string
export function getTempDir(): string
export function getCwd(): string

// search.rs exports
export interface SearchResult {
  id: string
  sessionId: string
  role: string
  content: string
  snippet: string
  rank: number
  timestamp: number
}

export interface MessageInput {
  id: string
  sessionId: string
  role: string
  content: string
  timestamp: number
  metadata?: string | null
}

export interface SessionInput {
  id: string
  title: string
  cwd?: string | null
  createdAt: number
  updatedAt: number
}

export function searchInit(): boolean
export function searchIndexMessage(message: MessageInput): boolean
export function searchIndexMessages(messages: MessageInput[]): number
export function searchMessages(query: string, limit?: number | null, sessionId?: string | null): SearchResult[]
export function searchGetContext(sessionId: string, limit?: number | null): SearchResult[]
export function searchFindSimilar(content: string, limit?: number | null, excludeSession?: string | null): SearchResult[]
export function searchDeleteSession(sessionId: string): number
export function searchGetStats(): string

// types.rs exports (LSP types)
export interface LspPosition {
  line: number
  character: number
}

export interface LspRange {
  start: LspPosition
  end: LspPosition
}

export interface LspCompletionItem {
  label: string
  kind?: number | null
  detail?: string | null
  documentation?: string | null
  insertText?: string | null
  sortText?: string | null
}

export interface LspDiagnostic {
  range: LspRange
  severity?: number | null
  code?: string | null
  source?: string | null
  message: string
  relatedInformation?: LspDiagnosticRelatedInformation[] | null
}

export interface LspDiagnosticRelatedInformation {
  location: LspLocation
  message: string
}

export interface LspLocation {
  uri: string
  range: LspRange
}

export interface LspSymbolInformation {
  name: string
  kind: number
  location: LspLocation
  containerName?: string | null
}

export interface LspWorkspaceEdit {
  changes?: Record<string, LspTextEdit[]> | null
}

export interface LspTextEdit {
  range: LspRange
  newText: string
}

export type GitStatusType = 'Modified' | 'Added' | 'Deleted' | 'Untracked'

export interface GitStatusEntry {
  path: string
  status: GitStatusType
}

export interface GitCommit {
  id: string
  message: string
  author: string
  email: string
  timestamp: number
}
